###  -*-Makefile-*-
# Copyright (c) 2018-2020 Bluespec, Inc. All Rights Reserved

# ================================================================

TOPFILE   := src/CPU.bs
TOPMODULE := mkCPU

include ../Include_Makefile.mk
